import type { Metadata } from "next";
import Link from "next/link";
import { CHANGELOG } from "@/lib/changelog";

export const metadata: Metadata = {
  title: "What's New — Daily Double",
  description: "Recent changes and improvements to Daily Double.",
};

const TAG_STYLES: Record<string, string> = {
  new: "bg-gold text-board-deep",
  improved: "bg-board text-blue-100 border border-blue-300/30",
  fixed: "bg-board-deep text-blue-200 border border-blue-300/20",
};

function formatDate(date: string): string {
  return new Date(`${date}T12:00:00`).toLocaleDateString("en-US", {
    month: "long",
    day: "numeric",
    year: "numeric",
  });
}

export default function ChangelogPage() {
  return (
    <div className="flex flex-col flex-1 min-h-screen">
      <main className="flex-1 w-full max-w-2xl mx-auto px-4 md:px-8 py-10">
        <header className="text-center mb-10">
          <h1 className="font-display text-4xl md:text-5xl tracking-wider text-gold">What&apos;s New</h1>
          <p className="text-blue-200/70 mt-2">Recent changes and improvements to Daily Double.</p>
          <Link href="/" className="inline-block mt-3 text-gold/80 hover:text-gold underline">
            ← Back to today&apos;s board
          </Link>
        </header>

        <ol className="relative border-l border-board pl-6 space-y-10">
          {CHANGELOG.map((entry, i) => (
            <li key={i} className="relative">
              <span className="absolute -left-[1.90rem] top-1.5 h-3 w-3 rounded-full bg-gold ring-4 ring-background" />
              <p className="font-mono text-xs uppercase tracking-widest text-blue-200/40 mb-1">
                {formatDate(entry.date)}
              </p>
              <div className="flex items-center gap-3 mb-3 flex-wrap">
                <h2 className="font-display text-2xl tracking-wide text-gold">{entry.title}</h2>
                {entry.tag && (
                  <span
                    className={`font-mono text-[10px] font-bold uppercase tracking-wider px-2 py-0.5 rounded-full ${
                      TAG_STYLES[entry.tag] ?? ""
                    }`}
                  >
                    {entry.tag}
                  </span>
                )}
              </div>
              <ul className="space-y-2">
                {entry.items.map((item, j) => (
                  <li key={j} className="flex gap-2.5 text-blue-100/85 leading-relaxed">
                    <span className="text-gold/60 select-none mt-0.5">›</span>
                    <span>{item}</span>
                  </li>
                ))}
              </ul>
            </li>
          ))}
        </ol>
      </main>
      <footer className="text-center text-xs text-blue-200/40 py-6">
        Built by Stanley Luong · Clues generated by Claude (Opus 4.8) · Not affiliated with Jeopardy!
      </footer>
    </div>
  );
}
