import Link from "next/link";
import { notFound } from "next/navigation";
import Game from "@/components/Game";

const ID_RE = /^[A-Za-z0-9]{6,}$/;

export default async function CustomBoardPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  if (!ID_RE.test(id)) notFound();

  return (
    <div className="flex flex-col flex-1 min-h-screen">
      <main className="flex-1 w-full px-4 md:px-8 py-10">
        <header className="text-center mb-8">
          <p className="font-mono text-xs uppercase tracking-[0.2em] text-gold/60 mb-1">Your custom board</p>
          <h1 className="font-display text-4xl md:text-6xl tracking-wider text-gold">Daily Double</h1>
          <p className="text-blue-200/70 mt-2">
            A one-round board from your categories, written by Claude.{" "}
            <Link href="/create" className="text-gold/80 hover:text-gold underline">
              Make another
            </Link>{" "}
            ·{" "}
            <Link href="/" className="text-gold/80 hover:text-gold underline">
              Today&apos;s board
            </Link>
          </p>
        </header>
        <Game date={`custom-${id}`} />
      </main>
      <footer className="text-center text-xs text-blue-200/40 py-6">
        Built by Stanley Luong · Clues generated by Claude (Opus 4.8) · Not affiliated with Jeopardy!
      </footer>
    </div>
  );
}
