import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { getBoardForDate } from "@/lib/jeopardy";
import { formatBoardDate, formatDuration, formatMoney } from "@/lib/format";
import { topScores } from "@/lib/scores";

const DATE_RE = /^\d{4}-\d{2}-\d{2}$/;

export async function generateMetadata({
  params,
}: {
  params: Promise<{ date: string }>;
}): Promise<Metadata> {
  const { date } = await params;
  return {
    title: `${date} leaderboard — Daily Double`,
    description: `Every score posted on the Daily Double board from ${date}.`,
  };
}

export default async function DateLeaderboardPage({
  params,
}: {
  params: Promise<{ date: string }>;
}) {
  const { date } = await params;
  if (!DATE_RE.test(date)) notFound();

  const board = await getBoardForDate(date).catch(() => null);
  if (!board) notFound();

  const scores = await topScores(date, 500).catch((error) => {
    console.error("topScores failed:", error);
    return [];
  });

  return (
    <div className="flex flex-col flex-1 min-h-screen">
      <main className="flex-1 w-full max-w-2xl mx-auto px-4 md:px-8 py-10">
        <header className="text-center mb-8">
          <h1 className="font-display text-4xl md:text-5xl tracking-wider text-gold">
            Leaderboard
          </h1>
          <p className="text-blue-200/70 mt-2">{formatBoardDate(date)}</p>
          <p className="mt-3 flex flex-wrap gap-x-4 gap-y-1 justify-center text-sm">
            <Link href={`/boards/${date}`} className="text-gold/80 hover:text-gold underline">
              Play this board
            </Link>
            <Link href="/boards" className="text-gold/80 hover:text-gold underline">
              All boards
            </Link>
          </p>
        </header>

        {scores.length === 0 ? (
          <p className="text-center text-blue-200/50 py-16">
            No scores posted for this board yet.
          </p>
        ) : (
          <ol className="divide-y divide-board bg-board-deep/40 border border-board rounded-lg overflow-hidden">
            {scores.map((row, i) => (
              <li key={`${row.name}-${i}`} className="flex items-center gap-3 px-4 py-2.5">
                <span className="text-blue-200/50 w-8 text-right tabular-nums">{i + 1}.</span>
                <span className="flex-1 truncate">{row.name}</span>
                <span className="text-blue-200/50 text-sm hidden sm:inline">
                  {row.correct}✓ {row.wrong}✗ {row.passed}–
                </span>
                <span className="text-blue-200/50 text-sm tabular-nums w-12 text-right">
                  {formatDuration(row.durationMs)}
                </span>
                <span
                  className={`font-display text-xl tracking-wide w-24 text-right ${
                    row.score < 0 ? "text-red-400" : "text-gold"
                  }`}
                >
                  {formatMoney(row.score)}
                </span>
              </li>
            ))}
          </ol>
        )}
      </main>
      <footer className="text-center text-xs text-blue-200/40 py-6">
        Built by Stanley Luong · Clues generated by Claude (Opus 4.8)
      </footer>
    </div>
  );
}
