import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import Game from "@/components/Game";

const DATE_RE = /^\d{4}-\d{2}-\d{2}$/;

export async function generateMetadata({
  params,
}: {
  params: Promise<{ date: string }>;
}): Promise<Metadata> {
  const { date } = await params;
  return {
    title: `${date} board — Daily Double`,
    description: `Replay the Daily Double board from ${date}.`,
  };
}

export default async function PastBoardPage({
  params,
}: {
  params: Promise<{ date: string }>;
}) {
  const { date } = await params;
  if (!DATE_RE.test(date)) notFound();

  return (
    <div className="flex flex-col flex-1 min-h-screen">
      <main className="flex-1 w-full px-4 md:px-8 py-10">
        <header className="text-center mb-8">
          <h1 className="font-display text-4xl md:text-6xl tracking-wider text-gold">
            Daily Double
          </h1>
          <p className="text-blue-200/70 mt-2">
            Replaying a past board.{" "}
            <Link href="/boards" className="text-gold/80 hover:text-gold underline">
              All boards
            </Link>{" "}
            ·{" "}
            <Link href="/" className="text-gold/80 hover:text-gold underline">
              Today&apos;s board
            </Link>
          </p>
        </header>
        <Game date={date} />
      </main>
      <footer className="text-center text-xs text-blue-200/40 py-6">
        Built by Stanley Luong · Clues generated by Claude (Opus 4.8) · Not affiliated with
        Jeopardy!
      </footer>
    </div>
  );
}
