import Game from "@/components/Game";

export default function Home() {
  return (
    <div className="flex flex-col flex-1 min-h-screen">
      <main className="flex-1 w-full px-4 md:px-8 py-10">
        <header className="text-center mb-8">
          <h1 className="font-display text-5xl md:text-7xl tracking-wider text-gold">
            Daily Double
          </h1>
          <p className="text-blue-200/70 mt-2 max-w-xl mx-auto">
            A new Jeopardy!-style board every day — six categories, thirty clues, written and
            judged by Claude. Type your answer; a lenient AI host rules on it.
          </p>
        </header>
        <Game />
      </main>
      <footer className="text-center text-xs text-blue-200/40 py-6">
        Built by Stanley Luong · Clues generated by Claude (Opus 4.8) · Not affiliated with
        Jeopardy!
      </footer>
    </div>
  );
}
