import Link from "next/link";
import Game from "@/components/Game";

export default function Home() {
  return (
    <div className="flex flex-col flex-1 min-h-screen">
      <main className="flex-1 w-full px-4 md:px-8 py-10">
        <header className="text-center mb-8">
          <h1 className="font-display text-5xl md:text-7xl tracking-wider text-gold">
            Daily Double
          </h1>
          <p className="text-blue-200/70 mt-2 max-w-xl mx-auto">
            A new Jeopardy!-style board every day — two rounds, 60 clues, Daily Doubles and all,
            written and judged by Claude. Type your answer; a lenient AI host rules on it.
          </p>
          <div className="mt-3 flex items-center justify-center gap-x-4 gap-y-1 text-sm flex-wrap">
            <Link href="/play" className="text-gold hover:text-gold-soft underline font-semibold">
              Choose a board →
            </Link>
            <Link href="/live" className="text-gold/80 hover:text-gold underline">
              Play with friends →
            </Link>
            <Link href="/history" className="text-gold/80 hover:text-gold underline">
              Real Jeopardy! archive →
            </Link>
            <Link href="/boards" className="text-gold/80 hover:text-gold underline">
              Past AI boards →
            </Link>
          </div>
        </header>
        <Game />
      </main>
      <footer className="text-center text-xs text-blue-200/40 py-6 space-y-1">
        <p className="flex items-center justify-center gap-x-3 gap-y-1 flex-wrap">
          <Link href="/changelog" className="hover:text-gold underline underline-offset-2">
            What&apos;s new
          </Link>
          <span aria-hidden>·</span>
          <Link href="/privacy" className="hover:text-gold underline underline-offset-2">
            Privacy
          </Link>
          <span aria-hidden>·</span>
          <Link href="/terms" className="hover:text-gold underline underline-offset-2">
            Terms
          </Link>
        </p>
        <p>
          Built by Stanley Luong · Clues generated by Claude (Opus 4.8) · Not affiliated with
          Jeopardy!
        </p>
      </footer>
    </div>
  );
}
