import Link from "next/link";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service — Daily Double",
  description: "The terms for using Daily Double, an independent AI-generated trivia game.",
};

const UPDATED = "July 22, 2026";
const CONTACT = "xstanz@gmail.com";

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="space-y-3">
      <h2 className="font-display text-2xl tracking-wide text-gold">{title}</h2>
      <div className="space-y-3 text-blue-100/80 leading-relaxed">{children}</div>
    </section>
  );
}

export default function TermsPage() {
  return (
    <div className="flex flex-col flex-1 min-h-screen">
      <main className="flex-1 w-full max-w-3xl mx-auto px-6 py-12">
        <header className="mb-10">
          <h1 className="font-display text-4xl md:text-5xl tracking-wider text-gold">Terms of Service</h1>
          <p className="text-blue-200/50 mt-2 text-sm">Last updated: {UPDATED}</p>
          <Link href="/" className="inline-block mt-4 text-gold/80 hover:text-gold underline">
            ← Back to Daily Double
          </Link>
        </header>

        <div className="space-y-8">
          <Section title="Acceptance">
            <p>
              By using Daily Double (the &ldquo;Service&rdquo;), you agree to these Terms. If you don&apos;t agree,
              please don&apos;t use the Service.
            </p>
          </Section>

          <Section title="The Service">
            <p>
              Daily Double is a free, AI-generated Jeopardy-style trivia game offered for entertainment. Boards, clues,
              and answer judging are produced by AI and are provided as-is. Features may change or be discontinued at any
              time.
            </p>
          </Section>

          <Section title="Your account">
            <p>
              You&apos;re responsible for activity under your account and for keeping your login secure. Provide accurate
              information when signing up, and don&apos;t impersonate others.
            </p>
          </Section>

          <Section title="Acceptable use">
            <p>You agree not to:</p>
            <ul className="list-disc pl-5 space-y-2">
              <li>abuse, exploit, reverse-engineer, or attempt to disrupt the Service;</li>
              <li>cheat, script, or otherwise gain an unfair advantage in games or rankings;</li>
              <li>
                harass, threaten, or send hateful, abusive, or unlawful content in chat, direct messages, display names,
                or custom board categories;
              </li>
              <li>use the Service for any illegal purpose.</li>
            </ul>
          </Section>

          <Section title="Your content">
            <p>
              You are responsible for the content you create — including custom board categories, chat messages, direct
              messages, and your display name. By submitting content, you grant us a limited license to store and display
              it as needed to operate the Service (for example, showing your message to other players in a game). We may
              remove content or suspend accounts that violate these Terms.
            </p>
          </Section>

          <Section title="AI-generated content">
            <p>
              Clues, answers, and answer judgments are generated by AI and may be inaccurate, incomplete, or occasionally
              wrong. They are provided for fun and are not authoritative. Don&apos;t rely on the Service as a source of
              factual truth.
            </p>
          </Section>

          <Section title="Not affiliated with Jeopardy!">
            <p>
              Daily Double is an independent, unofficial, fan-made game. It is{" "}
              <strong>not affiliated with, endorsed by, sponsored by, or connected to</strong> Jeopardy Productions,
              Inc., Sony Pictures, CBS Media Ventures, or the <em>Jeopardy!</em> television program. Names such as
              &ldquo;Jeopardy!&rdquo;, &ldquo;Double Jeopardy!&rdquo;, and &ldquo;Daily Double&rdquo; are the property of
              their respective owners and are used here only descriptively to refer to the well-known quiz-game format.
            </p>
          </Section>

          <Section title="No warranty">
            <p>
              The Service is provided &ldquo;as is&rdquo; and &ldquo;as available,&rdquo; without warranties of any kind,
              whether express or implied. We do not guarantee the Service will be uninterrupted, error-free, or that
              content will be accurate.
            </p>
          </Section>

          <Section title="Limitation of liability">
            <p>
              To the fullest extent permitted by law, we are not liable for any indirect, incidental, or consequential
              damages arising from your use of the Service. The Service is free, and it is provided without any monetary
              obligation on your part.
            </p>
          </Section>

          <Section title="Termination">
            <p>
              You may stop using the Service at any time. We may suspend or terminate access if you violate these Terms
              or to protect the Service and its players.
            </p>
          </Section>

          <Section title="Changes to these Terms">
            <p>
              We may update these Terms from time to time. Material changes will be reflected by updating the date at the
              top of this page. Continued use after changes means you accept the updated Terms.
            </p>
          </Section>

          <Section title="Contact">
            <p>
              Questions? Email{" "}
              <a href={`mailto:${CONTACT}`} className="text-gold hover:underline">
                {CONTACT}
              </a>
              .
            </p>
          </Section>

          <p className="text-blue-200/40 text-sm pt-4">
            See also our{" "}
            <Link href="/privacy" className="text-gold/70 hover:text-gold underline">
              Privacy Policy
            </Link>
            .
          </p>
        </div>
      </main>
    </div>
  );
}
