import type { Metadata } from "next";
import Link from "next/link";
import { listBoards, todayKey } from "@/lib/jeopardy";

export const dynamic = "force-dynamic";

export const metadata: Metadata = {
  title: "Past boards — Daily Double",
  description: "Every Daily Double board ever played — replay any day and post your score.",
};

function formatDate(date: string): string {
  return new Date(`${date}T12:00:00`).toLocaleDateString("en-US", {
    weekday: "short",
    month: "long",
    day: "numeric",
    year: "numeric",
  });
}

export default async function BoardsPage() {
  const boards = await listBoards().catch((error) => {
    console.error("listBoards failed:", error);
    return [];
  });
  const today = todayKey();

  return (
    <div className="flex flex-col flex-1 min-h-screen">
      <main className="flex-1 w-full max-w-3xl mx-auto px-4 md:px-8 py-10">
        <header className="text-center mb-8">
          <h1 className="font-display text-4xl md:text-5xl tracking-wider text-gold">
            Past Boards
          </h1>
          <p className="text-blue-200/70 mt-2">
            Replay any day&apos;s board and post your score to its leaderboard.
          </p>
          <Link href="/" className="inline-block mt-3 text-gold/80 hover:text-gold underline">
            ← Today&apos;s board
          </Link>
        </header>

        {boards.length === 0 ? (
          <p className="text-center text-blue-200/50 py-16">
            No boards yet — play today&apos;s game to create the first one.
          </p>
        ) : (
          <ul className="space-y-3">
            {boards.map((b) => (
              <li key={b.date}>
                <Link
                  href={b.date === today ? "/" : `/boards/${b.date}`}
                  className="block bg-board-deep/60 border border-board hover:border-gold/50 rounded-lg p-4 transition-colors"
                >
                  <div className="flex items-baseline justify-between gap-3">
                    <p className="font-display text-xl tracking-wide text-gold">
                      {formatDate(b.date)}
                      {b.date === today && (
                        <span className="ml-2 text-xs bg-gold text-board-deep rounded px-1.5 py-0.5 align-middle">
                          TODAY
                        </span>
                      )}
                    </p>
                    <p className="text-sm text-blue-200/60 whitespace-nowrap">
                      {b.topScore
                        ? `Top: ${b.topScore.name} · $${b.topScore.score.toLocaleString()}`
                        : "No scores yet"}
                    </p>
                  </div>
                  {b.categoryTitles.length > 0 && (
                    <p className="text-sm text-blue-200/50 mt-1 truncate">
                      {b.categoryTitles.join(" · ")}
                    </p>
                  )}
                </Link>
              </li>
            ))}
          </ul>
        )}
      </main>
      <footer className="text-center text-xs text-blue-200/40 py-6">
        Built by Stanley Luong · Clues generated by Claude (Opus 4.8)
      </footer>
    </div>
  );
}
