import type { Metadata } from "next";
import Link from "next/link";
import { listBoards, todayKey } from "@/lib/jeopardy";
import BoardsList from "@/components/BoardsList";

export const dynamic = "force-dynamic";

export const metadata: Metadata = {
  title: "AI daily boards — Daily Double",
  description: "Every AI-generated Daily Double board — replay any day and post your score.",
};

export default async function BoardsPage() {
  const boards = await listBoards().catch((error) => {
    console.error("listBoards failed:", error);
    return [];
  });
  const today = todayKey();

  return (
    <div className="flex flex-col flex-1 min-h-screen">
      <main className="flex-1 w-full max-w-3xl mx-auto px-4 md:px-8 py-10">
        <header className="text-center mb-8">
          <p className="font-mono text-xs uppercase tracking-[0.2em] text-gold/60 mb-1">
            AI-generated · written &amp; judged by Claude
          </p>
          <h1 className="font-display text-4xl md:text-5xl tracking-wider text-gold">AI Daily Boards</h1>
          <p className="text-blue-200/70 mt-2 max-w-xl mx-auto">
            A fresh AI-written board for every day since launch. Replay any day and post your score.
            Looking for real Jeopardy! episodes instead?{" "}
            <Link href="/archive" className="text-gold/80 hover:text-gold underline">
              Browse the archive →
            </Link>
          </p>
          <Link href="/" className="inline-block mt-3 text-gold/80 hover:text-gold underline">
            ← Today&apos;s board
          </Link>
        </header>

        <BoardsList boards={boards} today={today} />
      </main>
      <footer className="text-center text-xs text-blue-200/40 py-6">
        Built by Stanley Luong · Clues generated by Claude (Opus 4.8)
      </footer>
    </div>
  );
}
