import type { Metadata } from "next";
import Link from "next/link";
import { topRanked } from "@/lib/ranking";

export const dynamic = "force-dynamic";

export const metadata: Metadata = {
  title: "Ranked Leaderboard — Daily Double",
  description: "Top players by rating in ranked live games.",
};

export default async function RankingsPage() {
  const players = await topRanked(50).catch(() => []);

  return (
    <div className="flex flex-col flex-1 min-h-screen">
      <main className="flex-1 w-full max-w-2xl mx-auto px-4 md:px-8 py-10">
        <header className="text-center mb-8">
          <h1 className="font-display text-4xl md:text-5xl tracking-wider text-gold">Ranked Leaderboard</h1>
          <p className="text-blue-200/70 mt-2">
            Ratings from ranked live games. Elo-style — win against higher-rated players to climb faster.
          </p>
          <Link href="/live" className="inline-block mt-3 text-gold/80 hover:text-gold underline">
            ← Play with friends
          </Link>
        </header>

        {players.length === 0 ? (
          <p className="text-center text-blue-200/50 py-16">
            No ranked games played yet — start one in ranked mode to open the ladder.
          </p>
        ) : (
          <ol className="divide-y divide-board bg-board-deep/40 border border-board rounded-lg overflow-hidden">
            {players.map((p, i) => {
              const winRate = p.games > 0 ? Math.round((p.wins / p.games) * 100) : 0;
              return (
                <li key={p.uid} className="flex items-center gap-3 px-4 py-3">
                  <span
                    className={`font-display text-xl w-8 text-right ${
                      i === 0 ? "text-gold" : i < 3 ? "text-blue-100" : "text-blue-200/40"
                    }`}
                  >
                    {i + 1}
                  </span>
                  <div className="flex-1 min-w-0">
                    <p className="text-blue-100 truncate">{p.name}</p>
                    <p className="text-xs text-blue-200/50">
                      {p.games} game{p.games === 1 ? "" : "s"} · {p.wins} win{p.wins === 1 ? "" : "s"} · {winRate}%
                    </p>
                  </div>
                  <span className="font-display text-2xl tracking-wide text-gold tabular-nums">{p.rating}</span>
                </li>
              );
            })}
          </ol>
        )}
      </main>
      <footer className="text-center text-xs text-blue-200/40 py-6">
        Built by Stanley Luong · Clues generated by Claude (Opus 4.8) · Not affiliated with Jeopardy!
      </footer>
    </div>
  );
}
